vim.g.mapleader = " "
vim.api.nvim_set_keymap("i", "<C-H>", "<C-W>", {silent = true})
vim.api.nvim_set_keymap("n", "<C-h>", "<C-w>h", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<C-j>", "<C-w>j", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<C-k>", "<C-w>k", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<C-l>", "<C-w>l", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "[b", ":BufferLineCycleNext<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "]b", ":BufferLineCyclePrev<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<C-q>", ":bd<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<leader>l", ":bnext<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<leader>h", ":bprevious<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("v", "<C-y>", '"+y', {silent = true})
vim.api.nvim_set_keymap("n", "<C-i>", '"+P', {silent = true})
vim.api.nvim_set_keymap("n", "Y", "y$", {silent = true})
vim.api.nvim_set_keymap("n", "gd", "<cmd>lua vim.lsp.buf.definition()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<leader>e", ":NvimTreeToggle<CR>", {noremap = true, silent = true})
